@startuml
!theme mono
skinparam monochrome reverse

class Category 

class Home

class User 

abstract class Transaction {
    - isSettled() : boolean
    - getAmount()
}

class SimpleTransaction extends Transaction {
    - isSettled() : boolean 
}

class SplitTransaction extends Transaction { 
    - override isSettled() : boolean 
}

Transaction "*" --> "1" User
Transaction "1" --> "1" Category
User "*" --> "1" Home
Category "*" --> "1" Home
Transaction "1" --> "*" SimpleTransaction

@enduml
